# Generated by Django 5.1.5 on 2025-02-11 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="The date and time when the booking starts.",
                        verbose_name="Start Time",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="The date and time when the booking ends.",
                        verbose_name="End Time",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The total price for the booking.",
                        max_digits=10,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="The payment status for this booking.",
                        max_length=10,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        help_text="The status of the booking.",
                        max_length=10,
                        verbose_name="Booking Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the booking was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the booking was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "book",
                    models.CharField(
                        help_text="A reference or name for the booking.",
                        max_length=255,
                        verbose_name="Booking Reference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who made the booking.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        help_text="The venue being booked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="venues.venue",
                        verbose_name="Venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
