# Generated by Django 5.1.5 on 2025-02-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture of the user.",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
