# Generated by Django 5.1.5 on 2025-02-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                help_text="Defines the status of the user: Pending, Active, or Block.",
                max_length=20,
            ),
        ),
    ]
