# Generated by Django 5.1.5 on 2025-02-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_is_approved_customuser_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="The email address of the user (used for authentication).",
                max_length=255,
                unique=True,
            ),
        ),
    ]
