# Generated by Django 5.1.5 on 2025-01-28 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the venue (e.g., Grand Ballroom).",
                        max_length=255,
                        verbose_name="Venue Name",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="The full address of the venue.",
                        verbose_name="Venue Address",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="The city where the venue is located.",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="The state where the venue is located.",
                        max_length=100,
                        verbose_name="State",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        help_text="The zip code for the venue's location.",
                        max_length=10,
                        verbose_name="Zip Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the venue.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="The maximum number of people the venue can accommodate.",
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="An optional image of the venue.",
                        null=True,
                        upload_to="venue_images/",
                        verbose_name="Venue Image",
                    ),
                ),
                (
                    "hourly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for booking the venue per hour.",
                        max_digits=10,
                        verbose_name="Hourly Price",
                    ),
                ),
                (
                    "daily_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for booking the venue for a full day (24 hours).",
                        max_digits=10,
                        verbose_name="Daily Price",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the venue is currently available for booking.",
                        verbose_name="Availability",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the venue was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the venue was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The owner of the venue (admin user).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
                "ordering": ["-created_at"],
            },
        ),
    ]
