# Generated by Django 5.1.5 on 2025-02-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the venue.",
                        max_length=255,
                        verbose_name="Venue Name",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="The location of the venue (e.g., New York, CA).",
                        max_length=255,
                        verbose_name="Location",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="The complete address of the venue.",
                        verbose_name="Venue Address",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The general price for booking the venue.",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="The maximum number of people the venue can accommodate.",
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        help_text="Working hours of the venue (e.g., 9:00 AM - 9:00 PM).",
                        max_length=100,
                        verbose_name="Working Hours",
                    ),
                ),
                (
                    "available_dates",
                    models.TextField(
                        help_text="Comma separated list of available dates for booking (e.g., '2023-12-01,2023-12-02').",
                        verbose_name="Available Dates",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="An optional image representing the venue.",
                        null=True,
                        upload_to="venue_images/",
                        verbose_name="Venue Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A short description of the venue, e.g., its features or capacity.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the venue is available for booking.",
                        verbose_name="Availability",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discount percentage applicable for bookings. E.g., 10 for 10% discount.",
                        max_digits=5,
                        verbose_name="Discount",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the venue was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the venue was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The owner of the venue (admin user).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="users.customuser",
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
                "ordering": ["-created_at"],
            },
        ),
    ]
