# Generated by Django 5.1.5 on 2025-01-28 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_groups_and_more"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="owner",
            field=models.ForeignKey(
                help_text="The owner of the venue (admin user).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venues",
                to="users.customuser",
                verbose_name="Owner",
            ),
        ),
    ]
